esphome:
  name: splitflap
  friendly_name: Split Flap Display

button:
  - platform: template
    name: "Home Split Flap"
    on_press:
      - split_flap.home:
          id: split_flap_display

number:
  - platform: template
    id: offset_0
    name: "Module 0 Offset"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true

  - platform: template
    id: offset_1
    name: "Module 1 Offset"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true

  - platform: template
    id: offset_2
    name: "Module 2 Offset"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true

  - platform: template
    id: offset_3
    name: "Module 3 Offset"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true

  - platform: template
    id: offset_4
    name: "Module 4 Offset"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true

  - platform: template
    id: offset_5
    name: "Module 5 Offset"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 43
    optimistic: true
    restore_value: true

  - platform: template
    id: offset_6
    name: "Module 6 Offset"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true

  - platform: template
    id: offset_7
    name: "Module 7 Offset"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: -24
    optimistic: true
    restore_value: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components

i2c:
  sda: GPIO8
  scl: GPIO9
  frequency: 400khz

logger:
  level: DEBUG

api:

web_server:
  port: 80

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "SplitFlap Fallback"

text:
  - platform: split_flap
    name: "Display Text"
    id: split_flap_display
    mode: TEXT
    steps_per_rot: 2048
    magnet_position: 615
    display_offset: 0
    max_vel: 15.0
    home_on_startup: true
    modules:
      - address: 0x20
        offset: offset_0
      - address: 0x21
        offset: offset_1
      - address: 0x22
        offset: offset_2
      - address: 0x23
        offset: offset_3
      - address: 0x24
        offset: offset_4
      - address: 0x25
        offset: offset_5
      - address: 0x26
        offset: offset_6
      - address: 0x27
        offset: offset_7
